version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    steps:
      - checkout
      - run: go mod download
      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=$CIRCLE_SHA1-$CIRCLE_BUILD_NUM
          docker build -t docker.pkg.github.com/vinhut/uploader/uploader:$TAG .
          echo $GITHUB_TOKEN | docker login -u vinhut --password-stdin docker.pkg.github.com
          docker image ls -a
          docker push docker.pkg.github.com/vinhut/uploader/uploader:$TAG
